Make diagnostics relating to the callee hilight just the callee and put the caret on the ()'s.  e.g. produces:
t.c:13:9: error: called object is not a function or function pointer
  ((B)a)();
  ~~~~~~^

instead of:

t.c:13:3: error: called object is not a function or function pointer
  ((B)a)();
  ^~~~~~~~